version: "3"

services:
    db:
        image: postgres
        container_name: postgres_container
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
        - ./mysql/:/docker-entrypoint-initdb.d
    
    adminer:
        image: adminer
        container_name: adminer_container
        restart: always
        ports:
            - 8080:8080

    dash:
        container_name: dash_container
        build: "./dash"      
        ports:
            - 8055:8055         
        volumes:
            - "./dash/src:/src" 
        depends_on:
            - db
        
    jupyter:
        container_name: jupyter_container
        build: "./jupyter"
        ports:
            - 8888:8888
        volumes:
            - "./jupyter/src:/src" 
        depends_on:
            - db
        
        
